<?
$aMenuLinks = Array(
    Array(
        "Отзывы",
        "/partners/index.php",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Контакты",
        "/contacts",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Руководство",
        "/company/management.php",
        Array(),
        Array(),
        ""
    ),
    Array(
        "История",
        "/company/history.php",
        Array(),
        Array(),
        ""
    )
);
?>