<?
$aMenuLinks = Array(
    Array(
        "",
        "/index.php",
        Array(),
        Array("IMG"=>"/bitrix/templates/.default/images/nv_home.png"),
        ""
    ),
    Array(
        "Компания",
        "company/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Новости",
        "news/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Каталог",
        "catalog/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Фотогаллерея",
        "/index.php",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Партнерам",
        "partners/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Контакты",
        "contacts/",
        Array(),
        Array(),
        ""
    )
);
?>